#!/usr/bin/env python3
"""Generate the site's manual, safety, verification and release-notes pages from the code repository.

The texts are edited only in dedupcommando/DedupCommando. This script reads them at one pinned commit
(`upstream.lock`), rewrites their links for the site, and writes Zola content, two small data files and the
pictures the texts link to (`static/assets/manual/`).
Nothing it writes is committed (see .gitignore); rerun it before every build.

    python scripts/sync_docs.py --repo <checkout of the code repo> [--ref <commit>] [--tag <tag>] [--out <site>]

Without --ref/--tag the pin is read from upstream.lock ("<commit> <tag>"). Exit status 1 means the
source uses something this script does not know how to publish (a new kind of link, a missing anchor,
template syntax); fix the source or teach the script, never edit the generated files.
"""
from __future__ import annotations

import argparse
import json
import posixpath
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/dedupcommando/DedupCommando"
MARKER = "<!-- Generated by scripts/sync_docs.py from {src} at {ref} in the DedupCommando repository. Edit the source, not this file. -->"

CHAPTER_FILE_RE = re.compile(r"^(\d\d)-([a-z0-9-]+)\.md$")
NOTES_FILE_RE = re.compile(r"^(v\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?)\.md$")
VERSION_RE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.]+))?$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
LINK_RE = re.compile(r"(!?)\[((?:[^\[\]]|\[[^\]]*\])*)\]\(([^)\s]+)\)")
SCHEME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")
RAW_TAG_RE = re.compile(r"<([A-Za-z][A-Za-z0-9_-]*)(?=[\s>/])")

# Weak first paragraphs make weak search snippets; these chapters get a written description instead.
# Keep each one true to the chapter at the pinned commit and under 155 characters.
DESCRIPTION_OVERRIDES: dict[str, str] = {
    "docs/manual/01-intro.md":
        "What DedupCommando does and does not do, its requirements, the minimum safety guarantees to keep "
        "in mind, and who it was written for.",
    "docs/manual/06-classic.md":
        "The step-by-step wizard (dedcom --classic): scan setup, resuming scans, reviewing duplicate groups, "
        "marking actions, applying them and the summary.",
    "docs/manual/10-diff-trash.md":
        "ScanDiff compares two scans in six categories. The session trash soft-deletes old scan records in "
        "dedcom.db (not files) and purges them later.",
    "docs/manual/11-headless.md":
        "Run dedcom from scripts and cron without the TUI: --scan, --stats, --compact-db, --export-csv and "
        "--purge-quarantine, with their lock and exit codes.",
    "docs/manual/12-maintenance.md":
        "Where dedcom keeps its state, how large dedcom.db grows, VACUUM and retention settings, and rotating "
        "dedcom.log and benchmarks.log.",
}

# Headings of a released manual with a raw <placeholder>, which GitHub and the site would both swallow as HTML.
# The source is fixed in the next release; until then the site escapes exactly these lines at exactly this tag,
# or at exactly this commit when upstream.lock pins a docs-only commit after the tag (no tag field then).
# A listed line that is no longer found fails the sync, so the list cannot go stale unnoticed.
_V092_ESCAPES = {
    "docs/manual/13-troubleshooting.md": (
        '### "the group <hash> has files marked for an action and no keeper — choose the file to keep"',
        '### "cannot reflink on pool <pool> (N marks) — its block_cloning feature is disabled; '
        'mark HARDLINK or DELETE, or unmark; first: …"',
    ),
}
RAW_TAG_ESCAPES: dict[str, dict[str, tuple[str, ...]]] = {
    "v0.9.2": _V092_ESCAPES,
    # v0.9.2 plus docs-only commits: the manual matched to the code, then the scan GIF and the build note
    "d890b4728bdd35a074c7e62fa0c2e1d6133dce7b": _V092_ESCAPES,
    "a5e6c627f6b71b2663e9ae0db644111d66f268c1": _V092_ESCAPES,
}

# Pictures a published text links to are copied from the pinned commit into the site, flat, into one folder;
# the site never loads them from GitHub. SVG is left out on purpose: it can carry scripts.
IMAGE_EXTS = {".gif", ".png", ".jpg", ".jpeg", ".webp"}
IMAGE_DIR = ("static", "assets", "manual")
IMAGE_URL = "/assets/manual"

SITE_DOCS = {
    "docs/SAFETY.md": ("@/en/safety-model.md", "safety-model", 10,
                       "Safety, recovery and limitations — DedupCommando", "Safety, recovery and limitations"),
    "docs/VERIFYING-RELEASES.md": ("@/en/verifying-releases.md", "verifying-releases", 20,
                                   "Verifying DedupCommando releases — checksums, signatures, provenance",
                                   "Verifying releases"),
}


class SyncError(Exception):
    pass


def git(repo: str, *args: str) -> str:
    out = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, encoding="utf-8")
    if out.returncode != 0:
        raise SyncError(f"git {' '.join(args)}: {out.stderr.strip()}")
    return out.stdout


def version_key(tag: str) -> tuple:
    m = VERSION_RE.match(tag)
    if not m:
        return (-1,)
    major, minor, patch, pre = m.groups()
    # A release sorts after all of its pre-releases; pre-release parts compare numerically where possible.
    pre_key = (1,) if pre is None else (0, *[(int(p), "") if p.isdigit() else (-1, p) for p in pre.split(".")])
    return (int(major), int(minor), int(patch), pre_key)


def walk(lines: list[str]):
    """Yield (line, in_code) and keep track of fenced code blocks, including fences indented in lists."""
    fence: str | None = None
    for line in lines:
        m = FENCE_RE.match(line)
        if m:
            token = m.group(1)
            if fence is None:
                fence = token
                yield line, True
                continue
            if token[0] == fence[0] and len(token) >= len(fence) and line.strip() == token:
                fence = None
                yield line, True
                continue
        yield line, fence is not None


def strip_links(text: str) -> str:
    return LINK_RE.sub(lambda m: m.group(2), text)


def gh_anchor(heading: str, seen: dict[str, int]) -> str:
    """The id GitHub gives a heading: rendered text, lower case, punctuation dropped, spaces to hyphens."""
    text = strip_links(heading).strip().lower()
    slug = re.sub(r"[^\w\- ]", "", text).replace(" ", "-")
    count = seen.get(slug, 0)
    seen[slug] = count + 1
    return slug if count == 0 else f"{slug}-{count}"


def heading_ids(text: str) -> set[str]:
    seen: dict[str, int] = {}
    ids = set()
    for line, code in walk(text.splitlines()):
        if code:
            continue
        m = HEADING_RE.match(line)
        if m:
            ids.add(gh_anchor(m.group(2), seen))
    return ids


def first_paragraph(body_lines: list[str]) -> str:
    para: list[str] = []
    for line, code in walk(body_lines):
        s = line.strip()
        if code:
            if para:
                break
            continue
        if not s:
            if para:
                break
            continue
        if s.startswith(("#", "|", "---", "<")) or re.match(r"^([-*+]|\d+\.)\s", s):
            if para:
                break
            continue
        if s.startswith(">"):
            s = s.lstrip(">").strip()
            if not s:
                continue
        para.append(s)
    text = strip_links(" ".join(para))
    text = text.replace("`", "").replace("**", "")
    text = re.sub(r"(?<![\w*])\*(\S[^*]*?)\*(?![\w*])", r"\1", text)
    return re.sub(r"\s+", " ", text).strip()


def shorten(text: str, limit: int = 155) -> str:
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0].rstrip(",;:—–- ")
    return cut + "…"


def toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_value(v) for v in value) + "]"
    if isinstance(value, TomlDate):
        return value.text
    return json.dumps(str(value), ensure_ascii=False)


class TomlDate:
    def __init__(self, text: str):
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", text):
            raise SyncError(f"not a date: {text!r}")
        self.text = text


def front_matter(top: dict, extra: dict) -> str:
    lines = ["+++"]
    lines += [f"{k} = {toml_value(v)}" for k, v in top.items() if v is not None]
    lines.append("[extra]")
    lines += [f"{k} = {toml_value(v)}" for k, v in extra.items() if v is not None]
    lines.append("+++")
    return "\n".join(lines) + "\n"


class Upstream:
    def __init__(self, repo: str, ref: str, tag: str | None):
        self.repo = repo
        self.sha = git(repo, "rev-parse", f"{ref}^{{commit}}").strip()
        self.tag = tag
        if tag:
            tagged = git(repo, "rev-parse", f"{tag}^{{commit}}").strip()
            if tagged != self.sha:
                raise SyncError(f"tag {tag} is {tagged}, not the pinned commit {self.sha}")
        self.url_ref = tag or self.sha
        self.tree = {}
        for row in git(repo, "ls-tree", "-r", "-t", self.sha).splitlines():
            meta, path = row.split("\t", 1)
            self.tree[path] = meta.split()[1]

    def text(self, path: str) -> str:
        return git(self.repo, "show", f"{self.sha}:{path}")

    def blob(self, path: str) -> bytes:
        out = subprocess.run(["git", "-C", self.repo, "show", f"{self.sha}:{path}"], capture_output=True)
        if out.returncode != 0:
            raise SyncError(f"git show {path}: {out.stderr.decode('utf-8', 'replace').strip()}")
        return out.stdout

    def date(self, path: str) -> str:
        return git(self.repo, "log", "-1", "--format=%cs", self.sha, "--", path).strip()

    def released_tags(self) -> set[str]:
        return set(git(self.repo, "tag", "--merged", self.sha).split())

    def tag_date(self, tag: str) -> str:
        return git(self.repo, "for-each-ref", "--format=%(creatordate:short)", f"refs/tags/{tag}").strip()

    def blob_url(self, path: str) -> str:
        kind = self.tree.get(path)
        if kind not in ("blob", "tree"):
            raise SyncError(f"link to {path}, which does not exist at {self.sha}")
        return f"{REPO_URL}/{kind}/{self.url_ref}/{path}"


class Doc:
    """One source file and where it goes on the site."""

    def __init__(self, src: str, site_path: str, out_file: Path):
        self.src = src
        self.site_path = site_path
        self.out_file = out_file
        self.text = ""
        self.ids: set[str] = set()
        self.link_title = ""  # shown instead of a bare file path used as link text


def split_h1(text: str, src: str) -> tuple[str, list[str]]:
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if not line.strip():
            continue
        m = HEADING_RE.match(line)
        if not m or len(m.group(1)) != 1:
            raise SyncError(f"{src}: the first line must be the H1 heading")
        return m.group(2).strip(), lines[i + 1:]
    raise SyncError(f"{src}: empty file")


def transform(body: list[str], doc: Doc, docs: dict[str, Doc], up: Upstream, problems: list[str],
              images: dict[str, str]) -> str:
    out: list[str] = []
    seen: dict[str, int] = {}
    escapes = set(RAW_TAG_ESCAPES.get(up.tag or up.sha, {}).get(doc.src, ()))
    escaped: set[str] = set()

    def image(label: str, target: str) -> str:
        """A picture of the repository, published under IMAGE_URL; `images` maps its file name to its path."""
        if SCHEME_RE.match(target) or target.startswith("//"):
            problems.append(f"{doc.src}: image {target!r} is on another host — the site serves only its own files")
            return f"![{label}]({target})"
        repo_path = posixpath.normpath(posixpath.join(posixpath.dirname(doc.src), target.partition("#")[0]))
        name = posixpath.basename(repo_path)
        if up.tree.get(repo_path) != "blob" or posixpath.splitext(name)[1].lower() not in IMAGE_EXTS:
            problems.append(f"{doc.src}: image {target!r} is not an image file at {up.sha[:7]}")
            return f"![{label}]({target})"
        if images.setdefault(name, repo_path) != repo_path:
            problems.append(f"{doc.src}: two images named {name}: {images[name]} and {repo_path}")
        return f"![{label}]({IMAGE_URL}/{name})"

    def rewrite(m: re.Match) -> str:
        bang, label, target = m.groups()
        if bang:
            return image(label, target)
        if SCHEME_RE.match(target) or target.startswith("//"):
            return m.group(0)
        path, _, frag = target.partition("#")
        if not path:
            if frag not in doc.ids:
                problems.append(f"{doc.src}: anchor #{frag} does not exist in the same file")
            return m.group(0)
        repo_path = posixpath.normpath(posixpath.join(posixpath.dirname(doc.src), path))
        dest = docs.get(repo_path)
        if dest:
            if frag and frag not in dest.ids:
                problems.append(f"{doc.src}: anchor #{frag} does not exist in {repo_path}")
            if label.strip("`") == path and dest.link_title:
                label = dest.link_title  # "../SAFETY.md" reads badly on a web page
            return f"[{label}]({dest.site_path}{'#' + frag if frag else ''})"
        try:
            url = up.blob_url(repo_path)
        except SyncError as err:
            problems.append(f"{doc.src}: {err}")
            return m.group(0)
        return f"[{label}]({url}{'#' + frag if frag else ''})"

    for line, code in walk(body):
        if code:
            out.append(line)
            continue
        if "{{" in line or "{%" in line:
            problems.append(f"{doc.src}: template syntax outside code: {line.strip()[:80]}")
        heading = HEADING_RE.match(line)
        if heading:
            level, text = heading.groups()
            if len(level) == 1:
                problems.append(f"{doc.src}: a second H1 heading: {text}")
            anchor = gh_anchor(text, seen)
            shown = LINK_RE.sub(rewrite, text)
            if line in escapes:  # see RAW_TAG_ESCAPES; the anchor still comes from the source text
                shown = shown.replace("<", "&lt;").replace(">", "&gt;")
                escaped.add(line)
            out.append(f"{level} {shown} {{#{anchor}}}")
            continue
        out.append(LINK_RE.sub(rewrite, line))
    for line in sorted(escapes - escaped):
        problems.append(f"{doc.src}: RAW_TAG_ESCAPES line not found at {up.tag or up.sha[:7]}: {line[:80]}")
    for tag, where in raw_tags(["" if line in escaped else line for line in body]):
        problems.append(f"{doc.src}: raw <{tag}> outside code would be swallowed as HTML: {where}")
    return "\n".join(out).strip("\n") + "\n"


def raw_tags(body: list[str]):
    """Find <word> outside code. Code spans may continue onto the next line, so check whole paragraphs."""
    para: list[str] = []

    def flush():
        text = re.sub(r"(`+)(.+?)\1", "", "\n".join(para), flags=re.S)
        para.clear()
        for m in RAW_TAG_RE.finditer(text):
            yield m.group(1), text[max(0, m.start() - 30): m.end() + 30].replace("\n", " ")

    for line, code in walk(body):
        if code or not line.strip():
            yield from flush()
            continue
        para.append(line)
    yield from flush()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo", required=True, help="checkout of dedupcommando/DedupCommando")
    ap.add_argument("--ref", help="commit to publish (default: first field of upstream.lock)")
    ap.add_argument("--tag", help="release tag at that commit (default: second field of upstream.lock)")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[1]), help="site root")
    args = ap.parse_args()

    site = Path(args.out).resolve()
    if not args.ref:
        pin = (site / "upstream.lock").read_text(encoding="utf-8").split()
        args.ref = pin[0]
        args.tag = args.tag or (pin[1] if len(pin) > 1 else None)

    up = Upstream(args.repo, args.ref, args.tag)
    released = up.released_tags()

    # Where every published source file lands. Anchors are collected first so any file can link to any other.
    docs: dict[str, Doc] = {}
    manual_dir = site / "content" / "en" / "manual"
    changelog_dir = site / "content" / "en" / "changelog"
    chapters = sorted(p for p in up.tree if p.startswith("docs/manual/") and CHAPTER_FILE_RE.match(posixpath.basename(p)))
    if len(chapters) < 1:
        raise SyncError("no manual chapters found")
    docs["docs/manual/README.md"] = Doc("docs/manual/README.md", "@/en/manual/_index.md", manual_dir / "_index.md")
    for src in chapters:
        name = posixpath.basename(src)
        docs[src] = Doc(src, f"@/en/manual/{name}", manual_dir / name)
    for src, (site_path, stem, *_rest) in SITE_DOCS.items():
        docs[src] = Doc(src, site_path, site / "content" / "en" / f"{stem}.md")
    notes = []
    for path in sorted(up.tree):
        m = NOTES_FILE_RE.match(posixpath.basename(path)) if path.startswith("docs/release-notes/") else None
        if m and m.group(1) in released:
            notes.append((m.group(1), path))
            docs[path] = Doc(path, f"@/en/changelog/{m.group(1)}.md", changelog_dir / f"{m.group(1)}.md")
    if not notes:
        raise SyncError("no release notes with a released tag")
    for d in docs.values():
        d.text = up.text(d.src)
        d.ids = heading_ids(d.text)
        h1 = split_h1(d.text, d.src)[0]
        d.link_title = SITE_DOCS[d.src][4] if d.src in SITE_DOCS else re.sub(r"^\d\d\.\s+", "", h1).replace("`", "")

    problems: list[str] = []
    images: dict[str, str] = {}
    rendered: dict[str, tuple[str, str, list[str]]] = {}
    for src, d in docs.items():
        h1, body = split_h1(d.text, src)
        rendered[src] = (h1, transform(body, d, docs, up, problems, images), body)
    if problems:
        for p in problems:
            print(f"sync_docs: {p}", file=sys.stderr)
        return 1

    # Start from a clean slate so a chapter or picture removed upstream disappears from the site too.
    image_dir = site.joinpath(*IMAGE_DIR)
    for stale in (manual_dir, changelog_dir, image_dir):
        if stale.exists():
            shutil.rmtree(stale)
    manual_dir.mkdir(parents=True)
    changelog_dir.mkdir(parents=True)
    image_dir.mkdir(parents=True)
    for name, repo_path in sorted(images.items()):
        (image_dir / name).write_bytes(up.blob(repo_path))
    (site / "data").mkdir(exist_ok=True)

    def write(d: Doc, fm: str, body: str) -> None:
        marker = MARKER.format(src=d.src, ref=up.url_ref)
        with open(d.out_file, "w", encoding="utf-8", newline="\n") as f:
            f.write(fm + marker + "\n\n" + body)

    common = {"lang": "en", "dir": "ltr", "generated": True}
    source = lambda src: {"source_path": src, "source_ref": up.url_ref, "source_url": f"{REPO_URL}/blob/{up.url_ref}/{src}"}

    chapter_dates = []
    for src in chapters:
        d = docs[src]
        h1, body, raw = rendered[src]
        num, stem = CHAPTER_FILE_RE.match(posixpath.basename(src)).groups()
        m = re.match(r"^(\d\d)\.\s+(.+)$", h1)
        short = (m.group(2) if m else h1).replace("`", "")
        updated = up.date(src)
        chapter_dates.append(updated)
        description = DESCRIPTION_OVERRIDES.get(src) or shorten(first_paragraph(raw))
        fm = front_matter(
            {"title": f"{short} — DedupCommando manual", "description": description, "slug": stem,
             "weight": int(num), "updated": TomlDate(updated), "template": "manual-page.html"},
            {**common, "chapter": num, "h1": h1.replace("`", ""), "short_title": short, "schema": "TechArticle",
             "crumbs": ["docs", "manual"], **source(src)})
        write(d, fm, body)

    d = docs["docs/manual/README.md"]
    h1, body, raw = rendered[d.src]
    fm = front_matter(
        {"title": "DedupCommando user manual", "description": shorten(first_paragraph(raw)),
         "sort_by": "weight", "template": "manual-index.html", "page_template": "manual-page.html"},
        {**common, "h1": h1, "short_title": "Manual", "crumbs": ["docs"], "lastmod": max(chapter_dates),
         **source(d.src)})
    write(d, fm, body)

    for src, (site_path, stem, weight, title, short) in SITE_DOCS.items():
        d = docs[src]
        h1, body, raw = rendered[src]
        fm = front_matter(
            {"title": title, "description": shorten(first_paragraph(raw)), "weight": weight,
             "updated": TomlDate(up.date(src)), "template": "docs-page.html"},
            {**common, "h1": h1, "short_title": short, "schema": "TechArticle", "crumbs": ["docs"], **source(src)})
        write(d, fm, body)

    releases = []
    for tag, src in notes:
        d = docs[src]
        h1, body, raw = rendered[src]
        date = up.tag_date(tag)
        version = tag[1:]
        releases.append({"version": version, "tag": tag, "date": date, "url": f"{REPO_URL}/releases/tag/{tag}"})
        fm = front_matter(
            {"title": f"DedupCommando {tag} release notes", "description": shorten(first_paragraph(raw)),
             "date": TomlDate(date), "updated": TomlDate(up.date(src)), "path": f"en/changelog/{tag}",
             "template": "changelog-page.html"},
            {**common, "h1": f"DedupCommando {tag}", "short_title": tag, "version": version, "tag": tag,
             "schema": "TechArticle", "crumbs": ["docs", "changelog"],
             "release_url": f"{REPO_URL}/releases/tag/{tag}", **source(src)})
        write(d, fm, body)

    releases.sort(key=lambda r: version_key(r["tag"]), reverse=True)
    latest = releases[0]
    intro = ("What changed in each DedupCommando release, taken from the release notes in the project's "
             f"repository. Earlier pre-releases have notes only on [GitHub Releases]({REPO_URL}/releases). "
             "New notes are also available as an [Atom feed](atom.xml).\n")
    changelog_index = front_matter(
        {"title": "DedupCommando release notes", "sort_by": "date", "generate_feeds": True,
         "description": "Release notes for every DedupCommando version: what changes on upgrade, fixes, and actions to take.",
         "template": "changelog-index.html", "page_template": "changelog-page.html"},
        {**common, "h1": "Release notes", "short_title": "Release notes", "crumbs": ["docs"],
         "lastmod": latest["date"]})
    with open(changelog_dir / "_index.md", "w", encoding="utf-8", newline="\n") as f:
        f.write(changelog_index + "<!-- Generated by scripts/sync_docs.py. -->\n\n" + intro)

    with open(site / "data" / "release.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump({**latest, "ref": up.sha}, f, indent=2)
        f.write("\n")
    with open(site / "data" / "upstream-lastmod.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump([{"path": "/en/manual/", "lastmod": max(chapter_dates)},
                   {"path": "/en/changelog/", "lastmod": latest["date"]}], f, indent=2)
        f.write("\n")

    print(f"sync_docs: {len(chapters)} chapters, {len(SITE_DOCS)} docs, {len(notes)} release notes, "
          f"{len(images)} images from {up.url_ref} ({up.sha[:7]}); latest release {latest['tag']} {latest['date']}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SyncError as err:
        print(f"sync_docs: {err}", file=sys.stderr)
        sys.exit(1)
